<?php 
include "parts/header.php"
?>
<div class="main-banner">
<div class="main-banner-item banner-item-five">
<div class="container">
<div class="main-banner-content">
<h1>Global Digital Payments & Banking Partner</h1>
<p>Are You Looking To Bill Customers On A Recurring Basis?, Try Setting Up A Marketplace, Or Simply Accept Payments, You Can Do It All With A Fully Engineered Payments Infrastructure..</p>
<div class="banner-btn">
<a href="/signup" class="default-btn">Get started</a>
</div>
</div>
</div>
</div>
</div>

<section class="about-area bg-ffffff ptb-100">
<div class="container">
<div class="row">
<div class="col-lg-6">
<div class="about-image">
<a href="#" class="video-btn popup-youtube">
<i class='bx bx-play'></i>
</a>
</div>
</div>
<div class="col-lg-6">
<div class="about-content">
<span>Your gateway to recieve payments anywhere in the world</span>
<h3>We operate our banking services in many countries around the world.</h3>
<p>Are You a Financial Institution? Get Full Access To Global Payment Gateway Capabilities with our cutting Edge Seamless APIs, Integrate with our secure Infrastructure Now.</p>
<div class="about-btn">
<a href="/login" class="default-btn">Login Now</a>
</div>
</div>
</div>
</div>
</div>
</section>


<section class="fun-facts-area ptb-100">
<div class="container">
<div class="section-title">
<span>Why choose us</span>
<h2>Receive Fast, Global & Instant Payouts via Bank Transfer, Webmoney, Qiwi, MobileMoney, Mpesa, Visa/MasterCard</h2>
</div>
<div class="fun-facts-inner">
<div class="row">
<div class="col-lg-4 col-md-6 col-sm-6">
<div class="single-fun-fact">
<h3>
<span class="odometer" data-count="200+">00</span>
</h3>
<p>Happy customers</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6">
<div class="single-fun-fact">
<h3>
<span class="odometer" data-count="15+">00</span>
</h3>
<p>Mobile Money Operators</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6">
<div class="single-fun-fact">
<h3>
<span class="odometer" data-count="5+">00</span>
</h3>
<p>Banking Partners</p>
</div>
</div>

</div>
</div>
</div>
</section>


<section class="services-area bg-transparent pt-100 pb-70">
<div class="container">
<div class="section-title">

<span>Our services</span>
<h2>Our bank has been provided various banking services to our customers.</h2>
</div>
<div class="row">
<div class="col-lg-3 col-md-6">
<div class="single-services-item">
<div class="icon">
<i class="flaticon-mobile-banking"></i>
</div>
<h3>
<a href="#">Bank Transfers</a>
</h3>
<p>You can transfer from your wallet to any Bank in the world</p>
</div>
</div>

<div class="col-lg-3 col-md-6">
<div class="single-services-item">
<div class="icon">
<i class="flaticon-payment-security"></i>
</div>
<h3>
<a href="#">Mobile money wallet collections</a>
</h3>
<p>We collect from over 15 Mobile Money providers across Africa.</p>
</div>
</div>

<div class="col-lg-3 col-md-6">
<div class="single-services-item">
<div class="icon">
<i class="flaticon-credit-card"></i>
</div>
<h3>
<a href="#">Credit cards</a>
</h3>
<p>Customers can supply their card details and complete payment in a few minutes</p>
</div>
</div>

<div class="col-lg-3 col-md-6">
<div class="single-services-item">
<div class="icon">
<i class="flaticon-payment-security"></i>
</div>
<h3>
<a href="#">Mobile money Transfers</a>
</h3>
<p>We transfer to over 15 mobile money wallets Across Africa.</p>
</div>
</div>

</div>
</div>
</section>

<?php 
    include "parts/footer.php"
?>