<?php
	$users = $this->view_data['users'];
?>	
	
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Customers Overview</h2>
								
			
			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs mb-8">
				<div class="w-full overflow-x-auto">
					<div class="max-w-screen-lg mx-auto w-full h-full flex flex-col items-center justify-center">
						<div x-data="dataTable()"
							x-init="
							initData()
							$watch('searchInput', value => {
							  search(value)
							})" class="p-5 w-full flex flex-col dark:text-gray-400 dark:bg-gray-800 dark:border-gray-700">
							<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
								<div class="p-4">
									<input x-model="searchInput" type="text" class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" placeholder="Search by Reference, Email or Date">
								</div>
							</div>
							
							<table class="w-full whitespace-no-wrap" id="dataTable">
								<thead>
									<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
										<th class="px-4 py-3">Members</th>
										<th class="px-4 py-3">Contact Info</th>
										<th class="px-4 py-3">Status</th>
										<th class="px-4 py-3">Wallet</th>
										<th class="px-4 py-3">Action</th>
									</tr>
								</thead>
								<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
									<template x-for="(item, index) in items" :key="index">
										<tr x-show="checkView(index + 1)" class="text-sm text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<div class="flex items-center text-sm">
													<div>
														<p class="font-semibold" x-text="item.fullname"></p>
														<p class="text-xs text-gray-600 dark:text-gray-400 uppercase" x-text="item.role"></p>
													</div>
												</div>
											</td>
											<td class="px-4 py-3">
												<a x-bind:href="`mailto://${item.email}`" x-text="item.email"></a> 
												<br />
												<a x-bind:href="`tel://+${item.phone}`" x-text="item.phone"></a>
											</td>
											<template x-if="item.status == 'active'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-green-700 bg-green-100 dark:bg-green-700 dark:text-green-100" x-text="item.status"></span>
												</td>
											</template>
											<template x-if="item.status == 'inactive'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-red-700 bg-red-100 dark:bg-red-700 dark:text-red-100" x-text="item.status"></span>
												</td>
											</template>
											<template x-if="item.status == 'pending'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100" x-text="item.status"></span>
												</td>
											</template>
											<template x-if="item.status == 'review'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100" x-text="item.status"></span>
												</td>
											</template>
											<td class="px-4 py-3">
												UGX: <span x-text="item.ugx"></span></br>
												KES: <span x-text="item.kes"></span></br>
												USD: <span x-text="item.usd"></span>
											</td>
											<td>
												<button data-tippy-content="View Customer" class="px-2" id="myButton" type="button">
													<a x-bind:href="`<?=DOMAIN?>dashboard/customers/view?user=${item.reference}`" class="flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-blue-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
														<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
														  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
														  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
														</svg>
														 VIEW
													</a>
												</button>
											</td>
										</tr>
									</template>
									<tr x-show="isEmpty()">
										<td colspan="5" class="text-center py-3 text-gray-900 text-sm">No matching records found.</td>
									</tr>
								</tbody>
							</table>
							<div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
								<span class="flex items-center col-span-3"></span>
								<span class="col-span-2"></span>
								<!-- Pagination -->
								<span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
									<nav aria-label="Table navigation">
										<ul class="inline-flex items-center">
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple" aria-label="Previous" @click="changePage(currentPage - 1)">
													NEXT
												</button>
											</li>
											
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple" aria-label="Next" @click="changePage(currentPage + 1)">
													PREV
												</button>
											</li>
										</ul>
									</nav>
								</span>
							</div>
						</div>
					</div>		
				</div>
			</div>
			
		</div>
		
    </main>

<?php
$data = [];
foreach($users as $entry){
	array_push($data, array('fullname' => $entry->name,
							'role' => $entry->role,
							'email' => $entry->email,
							'phone' => $entry->phone,
							'reference' => $entry->ID,
							'ugx' => number_format($entry->ugx),
							'kes' => number_format($entry->kes),
							'usd' => number_format($entry->usd),
							'status' => $entry->status,
							'timestamp' => date('d F, Y', strtotime($entry->date))));
}
?>
<script>
let dati = <?=json_encode($data);?>;
</script>	
<!-- partial -->
<script src='https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js'></script>
<script  src="<?=DOMAIN?>assets/js/datatable.js"></script>  	
<!-- Production -->
<script src="https://unpkg.com/@popperjs/core@2" defer></script>
<script src="https://unpkg.com/tippy.js@6" defer></script>
<script>
    // With the above scripts loaded, you can call `tippy()` with a CSS
    // selector and a `content` prop:
    tippy('#myButton', {
        content: 'My tooltip!',
    });
</script>
</div>
</div>