<?php
	$users = $this->view_data['users'];
?>	
	<div class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center transition ease-out duration-150" style="display:none" id="modalBack">
		<!-- Modal -->
		<div class="w-full px-6 py-4 overflow-hidden bg-white rounded-t-lg dark:bg-gray-800 sm:rounded-lg sm:m-4 sm:max-w-xl transition ease-out duration-150" style="display:none; margin:auto !important;" role="dialog" id="modal">
			<!-- Remove header if you don't want a close icon. Use modal body to place modal tile. -->
			<header class="flex justify-end">
				<button class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700" aria-label="close" onclick="actionModal(false)">
					<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
					  <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" fill-rule="evenodd"></path>
					</svg>
				</button>
			</header>
			<!-- Modal body -->
			<div class="mt-4 mb-6">
				<!-- Modal title -->
				<p class="mb-2 text-lg font-semibold text-gray-700 dark:text-gray-300">
					Account Review Modal
				</p>
				<div class="mt-2 flex justify-center items-center mb-2" id="loading1">
					<div><img src="<?=DOMAIN?>assets/images/Rolling.gif" width="100" /></div>
				</div>
				<!-- Modal description -->
				<div id="callDiv">
					
				</div>
			</div>
			<footer class="flex flex-col items-center justify-end px-6 py-3 -mx-6 -mb-4 space-y-4 sm:space-y-0 sm:space-x-6 sm:flex-row bg-gray-50 dark:bg-gray-800">
				<button onclick="actionModal(false)" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
					Cancel
				</button>
				<button onclick="actionKYC(false)" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 border border-gray-300 rounded-lg dark:text-red-400 sm:px-4 sm:py-2 sm:w-auto active:bg-transparent hover:border-red-500 focus:border-red-500 active:text-red-500 focus:outline-none focus:shadow-outline-gray" style="background-color:red">
					Denied
				</button>
				<button onclick="actionKYC(true)" class="w-full px-5 py-3 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-blue-600 border border-transparent rounded-lg sm:w-auto sm:px-4 sm:py-2 active:bg-blue-600 hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue">
					Approve
				</button>
			</footer>
		</div>
    </div>
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Know your Customer Account</h2>
			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs mb-8">
				<div class="w-full overflow-x-auto">
					<div class="max-w-screen-lg mx-auto w-full h-full flex flex-col items-center justify-center">
						<div x-data="dataTable()"
							x-init="
							initData()
							$watch('searchInput', value => {
							  search(value)
							})" class="p-5 w-full flex flex-col dark:text-gray-400 dark:bg-gray-800 dark:border-gray-700">
							<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
								<div class="p-4">
									<input x-model="searchInput" type="text" class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" placeholder="Search by Reference, Email or Date">
								</div>
							</div>
							
							<table class="w-full whitespace-no-wrap" id="dataTable">
								<thead>
									<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
										<th class="px-4 py-3">Members</th>
										<th class="px-4 py-3">Contact Info</th>
										<th class="px-4 py-3">Date</th>
										<th class="px-4 py-3">Action</th>
									</tr>
								</thead>
								<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
									<template x-for="(item, index) in items" :key="index">
										<tr x-show="checkView(index + 1)" class="text-sm text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<div class="flex items-center text-sm">
													<div>
														<p class="font-semibold" x-text="item.fullname"></p>
													</div>
												</div>
											</td>
											<td class="px-4 py-3">
												<a x-bind:href="`mailto://${item.email}`" x-text="item.email"></a> 
												<br />
												<a x-bind:href="`tel://+${item.phone}`" x-text="item.phone"></a>
											</td>
											<td class="px-4 py-3">
												<span x-text="item.timestamp"></span>
											</td>
											<td>
												<div class="flex flex-row items-center text-sm">
													<button class="flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-blue-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" id="reviewBtn" x-bind:onclick="`openReviewer('${item.reference}')`"> REVIEW </button>
												</div>
											</td>
										</tr>
									</template>
									<tr x-show="isEmpty()">
										<td colspan="5" class="text-center py-3 text-gray-900 text-sm">No matching records found.</td>
									</tr>
								</tbody>
							</table>
							<div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
								<span class="flex items-center col-span-3"></span>
								<span class="col-span-2"></span>
								<!-- Pagination -->
								<span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
									<nav aria-label="Table navigation">
										<ul class="inline-flex items-center">
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple" aria-label="Previous" @click="changePage(currentPage - 1)">
													NEXT
												</button>
											</li>
											
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple" aria-label="Next" @click="changePage(currentPage + 1)">
													PREV
												</button>
											</li>
										</ul>
									</nav>
								</span>
							</div>
						</div>
					</div>		
				</div>
			</div>
			
		</div>
		
    </main>	
</div>
</div>
<script>
let modalBack = document.querySelector("#modalBack");
let modal = document.querySelector("#modal");
let callDiv = document.querySelector("#callDiv");
let loading1 = document.querySelector("#loading1");
let userID = '';
function openReviewer(mid){
	userID = mid;
	actionModal(true);
	fetchInfo(mid);
}

function actionModal(open){
	if(open){
		modal.style['display']  = 'block';
		modalBack.style['display']  = 'block';
	}else{
		modal.style['display']  = 'none';
		modalBack.style['display']  = 'none';
	}
}

function actionKYC(approve){
	if(approve){
		window.location.replace("<?=DOMAIN?>dashboard/kyc/update?user="+userID+"&action=1");
	}else{
		window.location.replace("<?=DOMAIN?>dashboard/kyc/update?user="+userID+"&action=0");
	}
}

function fetchInfo(mid){
	let formData = new URLSearchParams();
	formData.append('member_id', mid);

	console.log('rev');
	fetch('<?=DOMAIN?>reviewinfo', {
		method: 'POST',
		body: formData.toString(),
		headers: { 
			'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
		}
	})
	.then(response => response.text())
	.then(data => {
		// handle the response
		const obj = JSON.parse(data);
		
		loading1.classList.add('hidden');
		if(data == '[]'){
			callDiv.innerHTML = '<div class="flex flex-row"><p class="mb-1 text-sm font-medium text-gray-600 dark:text-gray-400">Document Submitted are Empty</p></div>';
		}else{
			callDiv.innerHTML = '<div class="flex flex-row"><p class="mb-1 text-sm font-medium text-gray-600 dark:text-gray-400">Submitted Document</p><img src="'+obj.source+'" width="200px" height="200px"/></div>';
		}
		
		
	})
	.catch(error => {
		// handle the error
		
	});
}
</script>
<?php
$data = [];
foreach($users as $entry){
	array_push($data, array('fullname' => $entry['fullname'],
							'role' => $entry['role'],
							'email' => $entry['email'],
							'phone' => $entry['phone_number'],
							'reference' => $entry['member_id'],
							'status' => $entry['status'],
							'timestamp' => date('d F, Y', strtotime($entry['created_date']))));
}
?>
<script>
let dati = <?=json_encode($data);?>;
</script>	
<!-- partial -->
<script src='https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js'></script>
<script  src="<?=DOMAIN?>assets/js/datatable.js"></script>  