<?php
	$account = $this->view_data['users'];
	
?>	
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
			<div class="flex items-stretch justify-items-stretch my-6 ">
				<h2 class="text-2xl font-semibold text-gray-700 dark:text-gray-200 w-1/2">Account Settings |</h2>
				<span class="px-4 py-1 uppercase font-semibold rounded-full <?=$color?>"><?=$account['role']?></span>
			</div>
			
			<form action="<?=DOMAIN?>dashboard/settings/saveinfo" method="POST">
			<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
				<label class="block mt-4 text-sm">
					<span class="text-gray-700 dark:text-gray-400">Full Name</span>
					<!-- focus-within sets the color for the icon when input is focused -->
					<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
						<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" name="fullname" placeholder="Firstname Lastname" value="<?=$account['fullname']?>" required>
					</div>
				</label>
				<label class="block mt-4 text-sm">
					<span class="text-gray-700 dark:text-gray-400">Phone Number</span>
					<!-- focus-within sets the color for the icon when input is focused -->
					<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
						<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" name="phone" placeholder="Phone" value="<?=$account['phone_number']?>" required>
					</div>
				</label>
				<label class="block mt-4 mb-4 text-sm">
					<span class="text-gray-700 dark:text-gray-400">
						Email Address
					</span>
					<div class="relative text-gray-500 focus-within:text-purple-600">
						<input class="block w-full pr-20 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" name="email" placeholder="yourself@email.com" value="<?=$account['email']?>" required>
					</div>
				</label>
            </div>
			<button class="p-2 text-sm font-medium leading-5 text-white rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" style="background-color:green"> Save Data </button>
			</form>
			
			<br/>
			
			<form action="<?=DOMAIN?>dashboard/settings/savepwd" method="POST">
			<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
				<label class="block mt-4 text-sm">
					<span class="text-gray-700 dark:text-gray-400">New Password</span>
					<!-- focus-within sets the color for the icon when input is focused -->
					<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
						<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" name="pwd" placeholder="Enter New Password Here" required>
					</div>
				</label>
				<label class="block mt-4 text-sm">
					<span class="text-gray-700 dark:text-gray-400">Retype Password</span>
					<!-- focus-within sets the color for the icon when input is focused -->
					<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
						<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" name="repwd" placeholder="Retype your new Password Here"  required>
					</div>
				</label>
            </div>
			<button class="p-2 text-sm font-medium leading-5 text-white rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" style="background-color:green"> Save New Password </button>
			</form>
			<br/>
		</div>
		
    </main>
	
</div>
</div>