<?php
	$navbar = $this->view_data['active'];
	$name = $this->view_data['name'];
	$email = $this->view_data['email'];
?>
<style>
.closeDiv {
	display: none !important;
}

.inner-anime {
    -webkit-transition: width 1s ease-in-out;
    -moz-transition: width 1s ease-in-out;
    -o-transition: width 1s ease-in-out;
    transition: width 1s ease-in-out;
}

</style>
<div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
		<!-- Desktop sidebar -->
		<aside class="z-20 hidden w-64 overflow-y-auto bg-white dark:bg-gray-800 md:block flex-shrink-0 shadow-md">
			<div class="py-4 text-gray-500 dark:text-gray-400">
				<a class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200" href="#">BluePlanet Pay</a>
				<ul class="mt-6">
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'wallets'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/home'?>">
							<svg
							  class="w-5 h-5"
							  aria-hidden="true"
							  fill="none"
							  stroke-linecap="round"
							  stroke-linejoin="round"
							  stroke-width="2"
							  viewBox="0 0 24 24"
							  stroke="currentColor"
							>
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
							</svg>
							<span class="ml-4">Dashboard</span>
						</a>
					</li>
				</ul>
				<ul>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'transactions'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/transactions'?>" >
							<svg
							  class="w-5 h-5"
							  aria-hidden="true"
							  fill="none"
							  stroke-linecap="round"
							  stroke-linejoin="round"
							  stroke-width="2"
							  viewBox="0 0 24 24"
							  stroke="currentColor"
							>
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2zM10 8.5a.5.5 0 11-1 0 .5.5 0 011 0zm5 5a.5.5 0 11-1 0 .5.5 0 011 0z" />
							</svg>
							<span class="ml-4">Performance</span>
						</a>
					</li>
					<li class="relative px-6 py-3">
						<button
							class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" onclick="openModal('main')"
						>
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
								</svg>
								<span class="ml-4">TopUp Wallet</span>
							</span>
							
						</button>
					</li>
					<li class="relative px-6 py-3">
						<button
							class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" onclick="openModal('comp')"
						>
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
								</svg>
								<span class="ml-4">Withdraw Money</span>
							</span>
							
						</button>
					</li>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'history'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<button
							class="inline-flex items-center justify-between w-full text-sm font-semibold transition-colors duration-150 text-gray-800 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100"
							@click="togglePagesMenu"
							aria-haspopup="true"
						>
							<span class="inline-flex items-center">
								<svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor" >
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
								</svg>
								<span class="ml-4">History</span>
							</span>
							<svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" >
								<path
								fill-rule="evenodd"
								d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
								clip-rule="evenodd" ></path>
							</svg>
						</button>
						<template x-if="isPagesMenuOpen">
							<ul
							  x-transition:enter="transition-all ease-in-out duration-300"
							  x-transition:enter-start="opacity-25 max-h-0"
							  x-transition:enter-end="opacity-100 max-h-xl"
							  x-transition:leave="transition-all ease-in-out duration-300"
							  x-transition:leave-start="opacity-100 max-h-xl"
							  x-transition:leave-end="opacity-0 max-h-0"
							  class="p-2 mt-2 space-y-2 overflow-hidden text-sm font-medium text-gray-500 rounded-md shadow-inner bg-gray-50 dark:text-gray-400 dark:bg-gray-900"
							  aria-label="submenu"
							>
								<li class="px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" >
									<a class="w-full" href="<?=DOMAIN.'portal/history/transfer'?>">Deposit History</a>
								</li>
								<li class="px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" >
									<a class="w-full" href="<?=DOMAIN.'portal/history/withdraw'?>">Withdraw History</a>
								</li>
							</ul>
						</template>
					</li>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'account'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/account'?>">
							<span class="inline-flex items-center">
								<svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
									<path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
								</svg>
								<span class="ml-4">API Settings</span>
							</span>
						</a>
					</li>
					<li class="relative px-6 py-3">
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="https://developer.blueplanetpay.com/" target="_blank">
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path d="M12 14l9-5-9-5-9 5 9 5z" />
									<path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
								</svg>
								<span class="ml-4">Documentations</span>
							</span>
						</a>
					</li>
				</ul>
				
			</div>
		</aside>

		
		<!-- Mobile sidebar -->
		<!-- Backdrop -->
		<div
			x-show="isSideMenuOpen"
			x-transition:enter="transition ease-in-out duration-150"
			x-transition:enter-start="opacity-0"
			x-transition:enter-end="opacity-100"
			x-transition:leave="transition ease-in-out duration-150"
			x-transition:leave-start="opacity-100"
			x-transition:leave-end="opacity-0"
			class="fixed inset-0 z-10 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center"
		></div>
		<aside
			class="fixed inset-y-0 z-20 flex-shrink-0 w-64 mt-16 overflow-y-auto bg-white dark:bg-gray-800 md:hidden"
			x-show="isSideMenuOpen"
			x-transition:enter="transition ease-in-out duration-150"
			x-transition:enter-start="opacity-0 transform -translate-x-20"
			x-transition:enter-end="opacity-100"
			x-transition:leave="transition ease-in-out duration-150"
			x-transition:leave-start="opacity-100"
			x-transition:leave-end="opacity-0 transform -translate-x-20"
			@click.away="closeSideMenu"
			@keydown.escape="closeSideMenu">
			<div class="py-4 text-gray-500 dark:text-gray-400">
				<a class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200" href="#" >BluePlanet Pay</a>
				<ul class="mt-6">
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'wallets'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/home'?>">
							<svg
							  class="w-5 h-5"
							  aria-hidden="true"
							  fill="none"
							  stroke-linecap="round"
							  stroke-linejoin="round"
							  stroke-width="2"
							  viewBox="0 0 24 24"
							  stroke="currentColor"
							>
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
							</svg>
							<span class="ml-4">Dashboard</span>
						</a>
					</li>
				</ul>
				<ul>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'transactions'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/transactions'?>" >
							<svg
							  class="w-5 h-5"
							  aria-hidden="true"
							  fill="none"
							  stroke-linecap="round"
							  stroke-linejoin="round"
							  stroke-width="2"
							  viewBox="0 0 24 24"
							  stroke="currentColor"
							>
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2zM10 8.5a.5.5 0 11-1 0 .5.5 0 011 0zm5 5a.5.5 0 11-1 0 .5.5 0 011 0z" />
							</svg>
							<span class="ml-4">Performance</span>
						</a>
					</li>
					<li class="relative px-6 py-3">
						<button
							class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" onclick="openModal('main')"
						>
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
								</svg>
								<span class="ml-4">TopUp Wallet</span>
							</span>
							
						</button>
					</li>
					<li class="relative px-6 py-3">
						<button
							class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" onclick="openModal('comp')"
						>
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
								</svg>
								<span class="ml-4">Withdraw Money</span>
							</span>
							
						</button>
					</li>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'history'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<button
							class="inline-flex items-center justify-between w-full text-sm font-semibold transition-colors duration-150 text-gray-800 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100"
							@click="togglePagesMenu"
							aria-haspopup="true"
						>
							<span class="inline-flex items-center">
								<svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor" >
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
								</svg>
								<span class="ml-4">History</span>
							</span>
							<svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" >
								<path
								fill-rule="evenodd"
								d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
								clip-rule="evenodd" ></path>
							</svg>
						</button>
						<template x-if="isPagesMenuOpen">
							<ul
							  x-transition:enter="transition-all ease-in-out duration-300"
							  x-transition:enter-start="opacity-25 max-h-0"
							  x-transition:enter-end="opacity-100 max-h-xl"
							  x-transition:leave="transition-all ease-in-out duration-300"
							  x-transition:leave-start="opacity-100 max-h-xl"
							  x-transition:leave-end="opacity-0 max-h-0"
							  class="p-2 mt-2 space-y-2 overflow-hidden text-sm font-medium text-gray-500 rounded-md shadow-inner bg-gray-50 dark:text-gray-400 dark:bg-gray-900"
							  aria-label="submenu"
							>
								<li class="px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" >
									<a class="w-full" href="<?=DOMAIN.'portal/history/transfer'?>">Deposit History</a>
								</li>
								<li class="px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" >
									<a class="w-full" href="<?=DOMAIN.'portal/history/withdraw'?>">Withdraw History</a>
								</li>
							</ul>
						</template>
					</li>
					<li class="relative px-6 py-3">
						<?php
							if($navbar == 'account'){ echo '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>';}
						?>
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<?=DOMAIN.'portal/account'?>">
							<span class="inline-flex items-center">
								<svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
									<path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
								</svg>
								<span class="ml-4">API Settings</span>
							</span>
						</a>
					</li>
					<li class="relative px-6 py-3">
						<a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="https://developer.blueplanetpay.com/" target="_blank">
							<span class="inline-flex items-center">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path d="M12 14l9-5-9-5-9 5 9 5z" />
									<path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
								</svg>
								<span class="ml-4">Documentations</span>
							</span>
						</a>
					</li>
				</ul>
			</div>
		</aside>
		
		
		
		<div class="flex flex-col flex-1 w-full">
			<header class="z-10 py-4 bg-white shadow-md dark:bg-gray-800">
				<div class="container flex items-center justify-between h-full px-6 mx-auto text-purple-600 dark:text-purple-300" >
					<!-- Mobile hamburger -->
					<button class="p-1 mr-5 -ml-1 rounded-md md:hidden focus:outline-none focus:shadow-outline-purple" @click="toggleSideMenu" aria-label="Menu" >
						<svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" >
							<path
							  fill-rule="evenodd"
							  d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
							  clip-rule="evenodd"
							></path>
						</svg>
					</button>
					<!-- Search input -->
					<div class="flex justify-center flex-1 lg:mr-32">
						<div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500" >
							
						</div>
					</div>
					<ul class="flex items-center flex-shrink-0 space-x-6">
						<!-- Theme toggler -->
						<li class="flex">
							<button class="rounded-md focus:outline-none focus:shadow-outline-purple" @click="toggleTheme" aria-label="Toggle color mode" >
								<template x-if="!dark">
									<svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" >
										<path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" ></path>
									</svg>
								</template>
								<template x-if="dark">
									<svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" >
									  <path
										fill-rule="evenodd"
										d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
										clip-rule="evenodd"
									  ></path>
									</svg>
								</template>
							</button>
						</li>
						
						<li class="flex">
							<div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500" >
								<h1 class="block text-md font-semibold text-gray-700 dark:text-gray-200 text-right"><?=$name?></h1>
								<small class="text-sm font-medium text-gray-600 dark:text-gray-400 text-right"><?=$email?></small>
							</div>
						</li>
						<!-- Profile menu -->
						<li class="relative">
							
							<button class="align-middle rounded-full focus:shadow-outline-purple focus:outline-none" @click="toggleProfileMenu" @keydown.escape="closeProfileMenu" aria-label="Account" aria-haspopup="true" >
								<img class="object-cover w-8 h-8 rounded-full" src="https://avatars.dicebear.com/api/initials/<?=$name?>.svg" alt="" aria-hidden="true" />
							</button>
							<template x-if="isProfileMenuOpen">
								<ul x-transition:leave="transition ease-in duration-150"
									x-transition:leave-start="opacity-100"
									x-transition:leave-end="opacity-0"
									@click.away="closeProfileMenu"
									@keydown.escape="closeProfileMenu"
									class="absolute right-0 w-56 p-2 mt-2 space-y-2 text-gray-600 bg-white border border-gray-100 rounded-md shadow-md dark:border-gray-700 dark:text-gray-300 dark:bg-gray-700"
									aria-label="submenu">
									<li class="flex">
										<a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200" href="<?=DOMAIN.'logout'?>" >
											<svg
											  class="w-4 h-4 mr-3"
											  aria-hidden="true"
											  fill="none"
											  stroke-linecap="round"
											  stroke-linejoin="round"
											  stroke-width="2"
											  viewBox="0 0 24 24"
											  stroke="currentColor"
											>
											  <path
												d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"
											  ></path>
											</svg>
											<span>Logout</span>
										</a>
									</li>
								</ul>
							</template>
						</li>
					</ul>
				</div>
			</header>
			
		
			<!--Overlay TopUp-->
			<div style="background-color: rgba(0,0,0,0.5)" id="mainModal" class="overflow-auto absolute inset-0 z-10 flex items-center justify-center closeDiv">
				<!--Dialog-->
				<div class="bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg py-4 text-left px-6 inner-anime">

					<!--Title-->
					<div class="flex justify-between items-center pb-3">
						<p class="text-2xl font-bold">Top Up Payment</p>
						<div class="cursor-pointer z-50" onclick="closeModal('main')">
							<svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
								<path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
							</svg>
						</div>
					</div>

					<!-- content -->
					<p>Enter your Phone Number and Amount to send.</p>
					
					<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input mt-4" type="number" placeholder="Phone Number" id="tpPhone" required>
					<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input my-4" type="number" placeholder="Amount" id="tpAmount" required>
					<select class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input mb-4" id="tpSelect" required>
						<option value="none" selected disabled>Choose Wallet to deposit fund</option>
						<option value="ugx">UGX</option>
						<option value="kes">KES</option>
					</select>
					
					<div class="mt-2 flex justify-center items-center mb-2" id="alerts1">
					</div>
					<!--Footer-->
					<div class="flex justify-end pt-2">
						<div id="loading1" class="hidden"><img src="<?=DOMAIN?>assets/images/Rolling.gif" width="50" /></div>
						<button class="px-4 bg-blue p-3 rounded-lg text-white mr-2" @click="topupPayment()">Submit</button>
						<button class="modal-close px-4 bg-red-600 p-3 rounded-lg text-white hover:bg-red-400" onclick="closeModal('main')">Close</button>
					</div>
					
				</div>
				<!-- End Dialog -->
			</div>
			<!-- End Overlay -->
			
			<!--Overlay Withdraw-->
			<div style="background-color: rgba(0,0,0,0.5)" id="compModal" class="overflow-auto absolute inset-0 z-10 flex items-center justify-center closeDiv">
				<!--Dialog-->
				<div class="bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg py-4 text-left px-6 inner-anime">
					<!--Title-->
					<div class="flex justify-between items-center pb-3">
						<p class="text-2xl font-bold">Withdraw Payment</p>
						<div class="cursor-pointer z-50" onclick="closeModal('comp')">
							<svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
								<path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
							</svg>
						</div>
					</div>

					<!-- content -->
					<p>Enter your Phone Number and Amount to send.</p>
					<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input mt-4" type="number" placeholder="Phone Number" id="wdPhone" required>
					<input class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input my-4" type="number" placeholder="Enter amount to withdraw" id="wdAmount" required>
					<select class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input mb-4" id="wdSelect" required>
						<option value="none" selected disabled>Choose Wallet to withdraw fund</option>
						<option value="ugx">UGX</option>
						<option value="kes">KES</option>
						<option value="usd">USD</option>
					</select>
					
					<div class="mt-2 flex justify-center items-center mb-2" id="alerts2">
					</div>
					<!--Footer-->
					<div class="flex justify-end pt-2">
						<div id="loading2" class="hidden"><img src="<?=DOMAIN?>assets/images/Rolling.gif" width="50" /></div>
						<button class="px-4 bg-blue p-3 rounded-lg text-white mr-2" onclick="withdrawPayment()">Withdraw</button>
						<button class="modal-close px-4 bg-red-600 p-3 rounded-lg text-white hover:bg-red-400" onclick="closeModal('comp')">Close</button>
						
					</div>
					

				</div>
				<!-- End Dialog -->
			</div>
			<!-- End Overlay -->
<script>
let mainModal = document.querySelector('#mainModal');
let compModal = document.querySelector('#compModal');
let tpPhone = document.querySelector('#tpPhone');
let tpAmount = document.querySelector('#tpAmount');
let tpSelect = document.querySelector('#tpSelect');
let wdPhone = document.querySelector('#wdPhone');
let wdAmount = document.querySelector('#wdAmount');
let wdSelect = document.querySelector('#wdSelect');
let divAlert1 = document.querySelector('#alerts1');
let divAlert2 = document.querySelector('#alerts2');
let loading1 = document.querySelector('#loading1');
let loading2 = document.querySelector('#loading2');
let divMain = document.querySelector('#divMain');

function openModal(mdname){
	if(mdname == 'main'){
		mainModal.classList.remove('closeDiv');
	}
	if(mdname == 'comp'){
		compModal.classList.remove('closeDiv');
	}
	
}
function closeModal(mdname){
	if(mdname == 'main'){
		mainModal.classList.add('closeDiv');
		divAlert1.innerHTML = '';
		loading1.classList.add('hidden');
		tpPhone.value = '';
		tpAmount.value = '';
	}
	if(mdname == 'comp'){
		compModal.classList.add('closeDiv');
		divAlert2.innerHTML = '';
		loading2.classList.add('hidden');
		wdPhone.value = '';
		wdAmount.value = '';
		wdSelect.value = 'none';
	}
	
}
function replace_phone(number){
  let new_number = ""
  if(number.startsWith("+")){
    new_number = number.replace(number[0], "");
  }
  else if(number.startsWith("0")){
    new_number = number.replace(number[0], "256");
  }
  else{
    new_number = number
  }
  return new_number;
}
function topupPayment(){
	if(tpPhone.value == '' || tpAmount.value == '' || tpSelect.value == 'none'){
		divAlert1.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Deposit Prompt</p>	<p>Fill all Fields First</p></div>';
	}else{
		loading1.classList.remove('hidden');
		divAlert1.innerHTML = '';
		let phone_num = tpPhone.value;
		tpPhone.value = replace_phone(phone_num);
		let formData = new URLSearchParams();
		formData.append('phone', tpPhone.value);
		formData.append('amount', tpAmount.value);
		formData.append('currency', tpSelect.value);

		fetch('<?=DOMAIN?>portal/action/deposit', {
			method: 'POST',
			body: formData.toString(),
			headers: { 
				'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
			}
		})
		.then(response => response.text())
		.then(data => {
			// handle the response
			const obj = JSON.parse(data);
			console.log(obj);
			if(obj.code == '200'){
				setTimeout('closeModal("main");', 10000);
				divAlert1.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-green-700 bg-green-100 rounded-lg" role="alert"><p class="font-bold">Deposit Successful</p>	<p>'+obj.message+'</p></div>';
			}else{
				divAlert1.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Deposit Failed</p>	<p>'+obj.message+'</p></div>';
			}
			//divMain.__x.$data.showModal = false;
			tpAmount.value = '';
			loading1.classList.add('hidden');
		})
		.catch(error => {
			// handle the error
			divAlert2.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Request Error</p>	<p>'+error+'</p></div>';
		});
	}
}

function withdrawPayment(){
	if(wdPhone.value == '' || wdAmount.value == '' || wdSelect.value == 'none'){
		divAlert2.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Withdraw Prompt</p>	<p>Fill all Fields First</p></div>';
	}else{
		loading2.classList.remove('hidden');
		divAlert2.innerHTML = '';
		let formData = new URLSearchParams();
		formData.append('currency', wdSelect.value);
		formData.append('phone', wdPhone.value);
		formData.append('amount', wdAmount.value);

		fetch('<?=DOMAIN?>portal/action/withdraw', {
			method: 'POST',
			body: formData.toString(),
			headers: { 
				'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
			}
		})
		.then(response => response.text())
		.then(data => {
			// handle the response
			//console.log(data);
			const obj = JSON.parse(data);
			console.log(obj);
			if(obj.code == '200'){
				setTimeout('closeModal("comp");', 10000);
				divAlert2.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-green-700 bg-green-100 rounded-lg" role="alert"><p class="font-bold">Withdraw Successful</p>	<p>'+obj.message+'</p></div>';
			}else{
				divAlert2.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Withdraw Failed</p>	<p>'+obj.message+'</p></div>';
			}
			//divMain.__x.$data.showComp = false;
			wdPhone.value = '';
			wdAmount.value = '';
			wdSelect.value = 'none';
			loading2.classList.add('hidden');
		})
		.catch(error => {
			// handle the error
			divAlert2.innerHTML = '<div class="w-full px-4 py-3 leading-normal text-orange-700 bg-orange-100 rounded-lg" role="alert"><p class="font-bold">Request Error</p>	<p>'+error+'</p></div>';
		});
	}
}
</script>
<script>
  function closeAlert(event){
    let element = event.target;
    while(element.nodeName !== "BUTTON"){
      element = element.parentNode;
    }
    element.parentNode.parentNode.removeChild(element.parentNode);
  }
</script>