<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	 <title><?php echo TITLE ?></title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo DOMAIN ?>assets/images/favicon.ico">

	<!-- CSS here -->
	<!-- <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/tailwindcss@2.1.1.min.css">
	<!-- <link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/style.css">-->
		
	<!-- JS here -->
	<!-- <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script> -->
	<script src="<?php echo DOMAIN ?>assets/js/alpine.min.js" defer></script>
	<script src="<?php echo DOMAIN ?>assets/vendor/animejs/anime.min.js"></script>
		
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@900&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
	<style>
		.Poppins {
			font-family: 'Poppins', sans-serif;
		}
		.Montserrat {
			font-family: 'Montserrat', sans-serif;
		}
		.Roboto {
			font-family: 'Roboto', sans-serif;
		}
	</style>
	
</head>