	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Customers Overview</h2>
								
			
			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs">
				<div class="w-full overflow-x-auto">
					<table class="w-full whitespace-no-wrap">
						<thead>
							<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
								<th class="px-4 py-3">Members</th>
								<th class="px-4 py-3">Contact Info</th>
								<th class="px-4 py-3">Status</th>
								<th class="px-4 py-3">Date</th>
								<th class="px-4 py-3">Action</th>
							</tr>
						</thead>
						<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
						
							<?php
								$users = $this->view_data['users'];
								foreach($users as $person){
									if($person['status'] == 'active'  ){ $color = 'text-green-700 bg-green-100 dark:bg-green-700 dark:text-green-100';}
									if($person['status'] == 'inactive'){ $color = 'text-red-700 bg-red-100 dark:bg-red-700 dark:text-red-100';}
									if($person['status'] == 'pending' ){ $color = 'text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100';}
									if($person['status'] == 'review'  ){ $color = 'text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100';}
									$date = date('d F, Y', strtotime($person['created_date'])); //July, 2017
									echo '<tr class="text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<div class="flex items-center text-sm">
													<div>
														<p class="font-semibold">'.$person['fullname'].'</p>
														<p class="text-xs text-gray-600 dark:text-gray-400 uppercase">'.$person['role'].'</p>
													</div>
												</div>
											</td>
											<td class="px-4 py-3 text-sm">
												<a href="mailto://'.$person['email'].'">'.$person['email'].'</a> 
												<br />
												<a href="tel://+'.$person['phone_number'].'">+'.$person['phone_number'].'</a>
											</td>
											<td class="px-4 py-3 text-xs">
												<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full '.$color.'">'.$person['status'].'</span>
											</td>
											<td class="px-4 py-3 text-sm">'.$date.'</td>
											<td>
												<div class="flex flex-row items-center text-sm">
													<button data-tippy-content="View Customer" class="px-2" id="myButton" type="button">
													<a href="customers/view/'.$person['member_id'].'" class="hover:shadow-md rounded-sm text-black">
														<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
														  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
														  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
														</svg>
													</a>
													</button>
													<button data-tippy-content="Delete Account" class="px-2" id="myButton" type="button">
													<a href="customers/delete/'.$person['member_id'].'" class="hover:shadow-md rounded-sm text-red-600">
														<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
														  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
														</svg>
													</a>
													</button>
												</div>
											</td>
										</tr>';
								}
							?>
							

						</tbody>
					</table>
				</div>
				
				<div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
					<span class="flex items-center col-span-3">Showing 21-30 of 100</span>
					<span class="col-span-2"></span>
					<!-- Pagination -->
					<span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
						<nav aria-label="Table navigation">
							<ul class="inline-flex items-center">
								<li>
									<button class="px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple" aria-label="Previous">
										<svg aria-hidden="true" class="w-4 h-4 fill-current" viewBox="0 0 20 20">
										<path
										  d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
										  clip-rule="evenodd"
										  fill-rule="evenodd"
										></path>
										</svg>
									</button>
								</li>
								<li>
									<button class="px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple">1</button>
								</li>
								<li>
									<button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">2</button>
								</li>
								<li>
									<button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">3</button>
								</li>
								<li>
									<button class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">4</button>
								</li>
								<li>
									<button class="px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple" aria-label="Next">
										<svg class="w-4 h-4 fill-current" aria-hidden="true" viewBox="0 0 20 20">
											<path
											  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
											  clip-rule="evenodd"
											  fill-rule="evenodd"
											></path>
										</svg>
									</button>
								</li>
							</ul>
						</nav>
					</span>
				</div>
			</div>

		</div>
    </main>
<!-- Production -->
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script>
    // With the above scripts loaded, you can call `tippy()` with a CSS
    // selector and a `content` prop:
    tippy('#myButton', {
        content: 'My tooltip!',
    });
</script>
</div>
</div>
  