<?php
	$tx = $this->view_data['list'];
	$status = $this->view_data['status'];
	$txsum = $this->view_data['txsum'];
	$txsum = count($txsum);
?>	
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Dashboard</h2>
			<?php
				//Check if Account is Not Verified
				$account_status = $this->view_data['member_status'];
				if($account_status == 'pending'){
					echo '<a class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-orange-700 bg-orange-100 rounded-lg shadow-md focus:outline-none focus:shadow-outline-red" href="'.DOMAIN.'portal/account/verification">
						<div class="flex items-center">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
							</svg>
							<span>This Account is not Active Yet, Please Upload your KYC information for review.</span>
						</div>
						<span>Upload Now →</span>
					</a>';
				}
			
			?>
			<!-- Cards -->
			<div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500">
						<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
							<path
							  d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
							></path>
						</svg>
					</div>
					<div>
						<p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">Account Status</p>
						<p class="text-lg font-semibold text-gray-700 dark:text-gray-200"><?=strtoupper($status)?></p>
					</div>
				</div>
				
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500">
						<svg
							  class="w-5 h-5"
							  aria-hidden="true"
							  fill="none"
							  stroke-linecap="round"
							  stroke-linejoin="round"
							  stroke-width="2"
							  viewBox="0 0 24 24"
							  stroke="currentColor"
							>
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
						</svg>
					</div>
					<div>
						<p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">Overall Transactions</p>
						<p class="text-lg font-semibold text-gray-700 dark:text-gray-200"><?=$txsum?></p>
					</div>
				</div>
				
			</div>

			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs mb-8">
				<div class="w-full overflow-x-auto">
					<table class="w-full whitespace-no-wrap" id="dataTable">
						<thead>
							<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
								<th class="px-4 py-3">Reference</th>
								<th class="px-4 py-3">Phone Number</th>
								<th class="px-4 py-3">Amount</th>
								<th class="px-4 py-3">Fee</th>
								<th class="px-4 py-3">Type</th>
								<th class="px-4 py-3">Status</th>
								<th class="px-4 py-3">Date</th>
							</tr>
						</thead>
						<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
						
							<?php
								//$users = $this->view_data['users'];
								foreach($tx as $entry){
									if($entry['status'] == 'success'  ){ $color = 'text-green-700 bg-green-100 dark:bg-green-700 dark:text-green-100';}
									if($entry['status'] == 'failed'){ $color = 'text-red-700 bg-red-100 dark:bg-red-700 dark:text-red-100';}
									if($entry['status'] == 'pending' ){ $color = 'text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100';}
									$date = date('d F, Y', strtotime($entry['tx_timestamp']));
									echo '<tr class="text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<div class="flex items-center text-sm">
													<div>
														<p class="font-semibold">'.$entry['email_address'].'</p>
														<p class="text-xs text-gray-600 dark:text-gray-400">'.$entry['txref'].'</p>
													</div>
												</div>
											</td>
											<td class="px-4 py-3 text-sm">
												<p class="font-semibold">'.$entry['mobile_number'].'</small></p>
											</td>
											<td class="px-4 py-3 text-sm">
												<p class="font-semibold">'.number_format($entry['total_amount']).'</p>
												<small> '.$entry['currency'].'</small>
											</td>
											<td class="px-4 py-3 text-sm">
												<p class="font-semibold">'.number_format($entry['amount_charge']).'</p>
												<small> '.$entry['currency'].'</small>
											</td>
											<td class="px-4 py-3 text-xs">
												<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-black dark:text-white">'.strtoupper($entry['tx_type']).'</span>
											</td>
											<td class="px-4 py-3 text-xs">
												<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full '.$color.'">'.$entry['status'].'</span>
											</td>
											<td class="px-4 py-3 text-sm">'.$date.'</td>
										</tr>';
								}
							?>
							

						</tbody>
					</table>
				</div>
			</div>

			
		</div>
    </main>
	
</div>
</div>