<?php
	$tx = $this->view_data['deposit'];
	$chart = $this->view_data['chart'];
	$numSuccess = $this->view_data['numSuccess'];
	$numFailed = $this->view_data['numFailed'];
?>	
	
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">Deposit History</h2>
			
			<div class="grid gap-6 mb-8 md:grid-cols-2">
								
				<div class="min-w-0 px-4">
					<!-- Card -->
					<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
						<div class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500">
							<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
							</svg>
						</div>
						<div>
							<p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">Number of Transactions</p>
							<p class="text-lg font-semibold text-gray-700 dark:text-gray-200"><?=number_format(count($tx));?></p>
						</div>
					</div>
					
					<div class="flex items-center mt-4 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
						<div class="p-3 mr-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500">
							<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
							</svg>
						</div>
						<div>
							<p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">Number of Successful Transactions</p>
							<p class="text-lg font-semibold text-gray-700 dark:text-gray-200"><?=number_format($numSuccess);?></p>
						</div>
					</div>
					
					<div class="flex items-center mt-4 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
						<div class="p-3 mr-4 text-red-600 bg-red-100 rounded-full dark:text-red-100 dark:bg-red-600">
							<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
							</svg>
						</div>
						<div>
							<p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">Number of Failed Transactions</p>
							<p class="text-lg font-semibold text-gray-700 dark:text-gray-200"><?=number_format($numFailed);?></p>
						</div>
					</div>
				</div>
				
				
				<div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">Yearly Transactions</h4>
					<canvas id="bars"></canvas>
					<div class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400">
						<!-- Chart legend -->
						<div class="flex items-center">
							<span class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"></span>
							<span>Number of Transactions</span>
						</div>
					</div>
				</div>
			</div>
			
			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs mb-8">
				<div class="w-full overflow-x-auto">
					<div class="max-w-screen-lg mx-auto w-full h-full flex flex-col items-center justify-center">
						<div x-data="dataTable()"
							x-init="
							initData()
							$watch('searchInput', value => {
							  search(value)
							})" class="p-5 w-full flex flex-col dark:text-gray-400 dark:bg-gray-800 dark:border-gray-700">
							<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
								<div class="p-4">
									<input x-model="searchInput" type="text" class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" placeholder="Search by Reference, Email or Date">
								</div>
							</div>
							
							<table class="w-full whitespace-no-wrap" id="dataTable">
								<thead>
									<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
										<th class="px-4 py-3">Reference</th>
										<th class="px-4 py-3">Amount</th>
										<th class="px-4 py-3">Fee</th>
										<th class="px-4 py-3">Status</th>
										<th class="px-4 py-3">Date</th>
									</tr>
								</thead>
								<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
									<template x-for="(item, index) in items" :key="index">
										<tr x-show="checkView(index + 1)" class="text-sm text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<div class="flex items-center text-sm">
													<div>
														<p class="text-xs text-gray-600 dark:text-gray-400 uppercase" x-text="item.reference"></p>
													</div>
												</div>
											</td>
											<td class="px-4 py-3">
												<p class="font-semibold" x-text="item.amount"> </p>
												<small x-text="item.currency"></small>
											</td>
											<td class="px-4 py-3">
												<p class="font-semibold" x-text="item.fee"></p>
												<small x-text="item.currency"> </small>
											</td>
											<template x-if="item.status == 'success'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-green-700 bg-green-100 dark:bg-green-700 dark:text-green-100" x-text="item.status"></span>
												</td>
											</template>
											<template x-if="item.status == 'failed'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-red-700 bg-red-100 dark:bg-red-700 dark:text-red-100" x-text="item.status"></span>
												</td>
											</template>
											<template x-if="item.status == 'pending'">
												<td class="px-4 py-3">
													<span class="px-2 py-1 uppercase font-semibold leading-tight rounded-full text-orange-700 bg-orange-100 dark:bg-yellow-700 dark:text-yellow-100" x-text="item.status"></span>
												</td>
											</template>
											<td class="px-4 py-3">
												<span x-text="item.timestamp"></span>
											</td>
										</tr>
									</template>
									<tr x-show="isEmpty()">
										<td colspan="5" class="text-center py-3 text-gray-900 text-sm">No matching records found.</td>
									</tr>
								</tbody>
							</table>
							<div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
								<span class="flex items-center col-span-3"></span>
								<span class="col-span-2"></span>
								<!-- Pagination -->
								<span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
									<nav aria-label="Table navigation">
										<ul class="inline-flex items-center">
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple" aria-label="Previous" @click="changePage(currentPage - 1)">
													NEXT
												</button>
											</li>
											
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple" aria-label="Next" @click="changePage(currentPage + 1)">
													PREV
												</button>
											</li>
										</ul>
									</nav>
								</span>
							</div>
						</div>
					</div>		
				</div>
			</div>
		</div>
    </main>
	
</div>
</div>
<script src="<?=DOMAIN?>assets/js/charts-lines.js" defer></script>
<script>
/**
 * For usage, visit Chart.js docs https://www.chartjs.org/docs/latest/
 */
const barConfig = {
  type: 'bar',
  data: {
    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    datasets: [{
        label: 'Transactions',
        backgroundColor: '#7e3af2',
        borderWidth: 1,
        data: [<?php foreach($chart as $month) {echo $month.',';}?>],
      },
    ],
  },
  options: {
    responsive: true,
    legend: {
      display: false,
    },
  },
}

const barsCtx = document.getElementById('bars')
window.myBar = new Chart(barsCtx, barConfig)
</script>
<?php
$data = [];
foreach($tx as $entry){
	array_push($data, array('email' => $entry['email_address'],
							'reference' => $entry['txref'],
							'amount' => number_format($entry['total_amount']),
							'currency' => $entry['currency'],
							'fee' => number_format($entry['amount_charge']),
							'status' => $entry['status'],
							'timestamp' => date('F d, Y h:i:s a', strtotime($entry['tx_timestamp']))));
}
?>
<script>
let dati = <?=json_encode($data);?>;
</script>	
<!-- partial -->
<script src='https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js'></script>
<script  src="<?=DOMAIN?>assets/js/datatable.js"></script>